site_name: Nefarius' Project Documentation
site_url: https://docs.nefarius.at
repo_url: https://github.com/nefarius/docs.nefarius.at
site_description: Projects devoted to USB input device emulation and game peripherals reverse engineering
copyright: |
  Copyright &copy; 2020 - 2023 <a href="https://github.com/nefarius" target="_blank" rel="noopener">Benjamin HÃ¶glinger-Stelzer</a>

theme:
  name: material
  favicon: images/favicon.png
  palette:
    primary: deep purple
  features:
    - navigation.tabs
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nefarius
    - icon: fontawesome/brands/discord
      link: https://discord.nefarius.at
extra_css:
  - stylesheets/extra.css
  - stylesheets/glightbox.css
  - stylesheets/toots.css
  - stylesheets/video.css
extra_javascript:
  - javascripts/glightbox.js
  - javascripts/main.js  

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details:
  - pymdownx.tilde:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
